# Generated by Django 4.0.2 on 2022-03-01 07:01

from django.db import migrations, models
import links.validators


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortenedlink',
            name='destination',
            field=models.CharField(max_length=200, validators=[links.validators.validate_url_exists], verbose_name='Куда ведет'),
        ),
    ]
